__title__ = 'with-env'
__description__ = 'with-env - Start a process with the nearby .env!'
__version__ = '0.2.0'
__author__ = 'Enzo CACERES'
__author_email__ = 'caceresenzo1502@gmail.com'
__url__ = 'https://github.com/Caceresenzo/with-env'
